services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=apisolid
